### basic http calls to api
http://localhost:8081/white
###
http://localhost:8081/black


### call through gateway
http://localhost:8080/white
Authorization: Bearer mario@rossi.it

### call through gateway
http://localhost:8080/white
Authorization: Key keyFake

### call through gateway for black
http://localhost:8080/black
Authorization: Bearer mario@rossi.it